export const ICEBREAKERS = [
  "If you could have dinner with any historical figure, who would it be?",
  "What is the most adventurous thing you've ever done?",
  "Would you rather travel 100 years into the past or 100 years into the future?",
  "What's your absolute favorite movie or TV show of all time?",
  "If you had to eat only one food for the rest of your life, what would it be?",
  "What's the best piece of advice you've ever received?",
  "If you could have any superpower, what would it be and why?",
  "What's your go-to karaoke song?",
  "Are you a morning person or a night owl?",
  "What's the most unusual skill you have?",
  "If you could live anywhere in the world, where would it be?",
  "What is your dream job?",
  "What's the last book you read or show you binge-watched?",
  "If you won the lottery tomorrow, what's the first thing you would buy?",
  "What is your favorite hobby or pastime?",
  "What is the most interesting place you've ever visited?",
  "Do you prefer dogs, cats, or something else?",
  "What's the best concert you've ever been to?",
  "If you could speak any language fluently, which one would it be?",
  "What's your favorite season of the year?",
  "Are you more of an introvert or an extrovert?",
  "If you could instantly learn any instrument, which one would it be?",
  "What's your favorite childhood memory?",
  "What is something you're looking forward to in the next month?",
  "Would you rather explore space or the deep ocean?",
  "What is your favorite board game or video game?",
  "If you could visit any planet, which one would it be?",
  "What's the funniest joke you know by heart?",
  "What is one thing on your bucket list?",
  "What's your favorite dessert or sweet treat?",
  "If you could change one thing about the world, what would it be?",
  "What's the most creative thing you've ever made?",
  "What's your favorite way to unwind after a long day?"
];
